global using Dalamud.Game.ClientState.Objects.Types;
global using Dalamud.Interface;
global using Dalamud.Interface.Utility;
global using Dalamud.Plugin;
global using ECommons.DalamudServices;
global using ECommons.DalamudServices.Legacy;
global using ECommons.ImGuiMethods;
global using ECommons.Logging;
global using ECommons.Schedulers;
global using ImGuiNET;
global using Splatoon.Services;
global using Splatoon.Utility;
global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.IO;
global using System.IO.Compression;
global using System.Linq;
global using System.Numerics;
global using System.Runtime.ExceptionServices;
global using System.Text;
global using System.Threading.Tasks;
global using static ECommons.GenericHelpers;
global using static ECommons.LanguageHelpers.Localization;
global using static Splatoon.Splatoon;
global using static Splatoon.Utility.Shortcuts;