# This is a basic workflow that is manually triggered

name: Generate script update data

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    paths:
      - SplatoonScripts/**

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  generate_updatefile:
    if: ${{ github.repository == 'PunishXIV/Splatoon' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            submodules: false
        - name: Set up .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - name: Run the program
          run: dotnet run --project ScriptUpdateFileGenerator/ScriptUpdateFileGenerator.csproj "SplatoonScripts" "SplatoonScripts/update.csv"
        - name: Commit file
          run: |
            git config --local user.email "noreply@nightmarexiv.com"
            git config --local user.name "GitHub Action"
            git add SplatoonScripts/update.csv
            git commit -m "Update SplatoonScripts/update.csv" -a || echo "No changes to commit"
            git push  # Push the changes back to the repository
